name: FullVendor
description: Full vendor management solution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.4+30

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutterlifecyclehooks: ^4.0.0
  fluttertoast: ^8.2.5
  http: ^1.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.19.0
  easy_localization: ^3.0.7
  decimal: ^2.3.3
  auto_size_text: ^3.0.0
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.1.2
  device_info_plus: ^10.1.0
  workmanager: ^0.5.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/raw/
    - assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 24